//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecModelEntities : DbContext
    {
        public RecModelEntities()
            : base("name=RecModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        //public virtual dbset<c__migrationhistory> c__migrationhistory { get; set; }
        //public virtual dbset<aspnetroles> aspnetroles { get; set; }
        //public virtual dbset<aspnetuserclaims> aspnetuserclaims { get; set; }
        //public virtual dbset<aspnetuserlogins> aspnetuserlogins { get; set; }
        //public virtual dbset<aspnetusers> aspnetusers { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Reponse> Reponse { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<Test_Question> Test_Question { get; set; }
        public virtual DbSet<Resultat_Test> Resultat_Test { get; set; }
    }
}
