//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultat_Test
    {
        public int Id { get; set; }
        public string note { get; set; }
        public string date_affectation { get; set; }
        public string date_expiration { get; set; }
       // public int TestId { get; set; }
        //public string AspNetUsersId { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual ApplicationUser Candidat { get; set; }
    }
}
