//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Question
    {
        public int Id { get; set; }
        //public Nullable<int> Test_id { get; set; }
       // public Nullable<int> Question_id { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Test Test { get; set; }
    }
}
